// NTLM-Analyzer - find out who still uses NTLM in your Active Directory.
// Copyright (C) 2026  Nobrac / Carbon / NoPCAP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! Windows service: SCM dispatcher, control handler and install/uninstall.
//!
//! The service starts automatically and is controllable via services.msc or
//! `sc start|stop NtlmAgent`. On a crash it is restarted automatically
//! (recovery actions, configured via sc.exe failure).
//!
//! The actual Windows implementation depends on the `windows-service` and
//! `winreg` crates and is only compiled for the Windows target. Other targets
//! get stubs with identical signatures so the project type-checks everywhere.

const SERVICE_NAME: &str = "NtlmAgent";
const DISPLAY_NAME: &str = "NTLM-Analyzer Agent";

#[cfg(not(windows))]
pub use stub_impl::{harden_data_dir, install, run, uninstall};
#[cfg(windows)]
pub use windows_impl::{harden_data_dir, install, run, uninstall};

#[cfg(windows)]
mod windows_impl {
    use super::{DISPLAY_NAME, SERVICE_NAME};
    use crate::{agent, config};
    use std::ffi::OsString;
    use std::sync::mpsc;
    use std::time::Duration;

    use windows_service::{
        define_windows_service,
        service::{
            ServiceAccess, ServiceControl, ServiceControlAccept, ServiceErrorControl,
            ServiceExitCode, ServiceInfo, ServiceStartType, ServiceState, ServiceStatus,
            ServiceType,
        },
        service_control_handler::{self, ServiceControlHandlerResult},
        service_dispatcher,
        service_manager::{ServiceManager, ServiceManagerAccess},
    };

    type R = Result<(), Box<dyn std::error::Error>>;

    const SERVICE_TYPE: ServiceType = ServiceType::OWN_PROCESS;

    // Generates the FFI entry point pair for the service control manager.
    define_windows_service!(ffi_service_main, service_main);

    /// Called by `main` for the `service` subcommand: hands control over to the
    /// SCM. Blocks until the service stops.
    pub fn run() -> R {
        service_dispatcher::start(SERVICE_NAME, ffi_service_main)?;
        Ok(())
    }

    /// Called by the SCM (through the FFI generated by define_windows_service!).
    fn service_main(_arguments: Vec<OsString>) {
        if let Err(e) = run_service() {
            config::log(&format!("service exited with an error: {e}"));
        }
    }

    fn run_service() -> R {
        // Stop signal: the control handler (another thread) sends, the loop waits.
        let (tx, rx) = mpsc::channel::<()>();

        let event_handler = move |control_event| -> ServiceControlHandlerResult {
            match control_event {
                ServiceControl::Stop | ServiceControl::Shutdown => {
                    let _ = tx.send(());
                    ServiceControlHandlerResult::NoError
                }
                ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,
                _ => ServiceControlHandlerResult::NotImplemented,
            }
        };

        let status_handle = service_control_handler::register(SERVICE_NAME, event_handler)?;

        let set_state = |state: ServiceState, accept: ServiceControlAccept| -> R {
            status_handle.set_service_status(ServiceStatus {
                service_type: SERVICE_TYPE,
                current_state: state,
                controls_accepted: accept,
                exit_code: ServiceExitCode::Win32(0),
                checkpoint: 0,
                wait_hint: Duration::default(),
                process_id: None,
            })?;
            Ok(())
        };

        set_state(
            ServiceState::Running,
            ServiceControlAccept::STOP | ServiceControlAccept::SHUTDOWN,
        )?;
        config::log("Service started.");

        // Load the configuration once. Without a valid configuration the service
        // cannot do anything useful -> stop cleanly instead of looping on errors.
        let cfg = match config::Config::load() {
            Ok(c) => c,
            Err(e) => {
                config::log(&format!("configuration not loadable: {e} - service stops."));
                set_state(ServiceState::Stopped, ServiceControlAccept::empty())?;
                return Ok(());
            }
        };

        let interval = Duration::from_secs(u64::from(cfg.interval_minutes.max(1)) * 60);

        loop {
            // Run one collect/push cycle. Catch panics so a single bad run does
            // not terminate the service (it is meant to run permanently).
            let res =
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| agent::run_cycle(&cfg)));
            match res {
                Ok(Ok(())) => {}
                Ok(Err(e)) => config::log(&format!("cycle error: {e}")),
                Err(_) => config::log("cycle panic caught - service keeps running."),
            }

            // Wait for the next interval OR wake up immediately on a stop signal.
            match rx.recv_timeout(interval) {
                Ok(()) => break,                                    // stop/shutdown
                Err(mpsc::RecvTimeoutError::Timeout) => continue,   // next cycle
                Err(mpsc::RecvTimeoutError::Disconnected) => break, // sender gone
            }
        }

        config::log("Service stopping.");
        set_state(ServiceState::Stopped, ServiceControlAccept::empty())?;
        Ok(())
    }

    /// Protected install location for the EXE. The default ACL of
    /// C:\Program Files erlaubt nur Administratoren/SYSTEM Schreibzugriff - damit
    /// the service does not run from a user-writable folder (e.g. Downloads),
    /// which would otherwise allow local privilege escalation.
    fn install_dir() -> std::path::PathBuf {
        let pf =
            std::env::var("ProgramFiles").unwrap_or_else(|_| String::from(r"C:\Program Files"));
        std::path::PathBuf::from(pf).join("NtlmAgent")
    }

    /// True if both paths point to the same file (re-install from the target dir).
    fn same_file(a: &std::path::Path, b: &std::path::Path) -> bool {
        match (a.canonicalize(), b.canonicalize()) {
            (Ok(x), Ok(y)) => x == y,
            _ => false,
        }
    }

    /// Restricts the ACL of C:\ProgramData\NtlmAgent to SYSTEM and Administrators
    /// (by SID, so it works regardless of the system language). Prevents normal
    /// users from redirecting config.json - and with it the telemetry target.
    /// Not fatal: if icacls fails it is logged and the installation continues.
    /// Public so the `configure` path (used by the MSI, which owns the files
    /// and the service itself) can lock the data folder down without going
    /// through the full `install`.
    pub fn harden_data_dir() {
        let dir = config::data_dir();
        let _ = std::fs::create_dir_all(&dir);
        let status = std::process::Command::new(config::system32("icacls.exe"))
            .arg(&dir)
            .args([
                "/inheritance:r",
                "/grant:r",
                "*S-1-5-18:(OI)(CI)F",     // SYSTEM
                "*S-1-5-32-544:(OI)(CI)F", // BUILTIN\Administratoren
            ])
            .status();
        match status {
            Ok(s) if s.success() => {
                config::log("ACL des Datenordners auf SYSTEM + Administratoren beschraenkt.")
            }
            Ok(s) => config::log(&format!(
                "icacls exited with status {s} - please check the data folder ACL manually."
            )),
            Err(e) => config::log(&format!(
                "could not run icacls: {e} - please set the data folder ACL manually."
            )),
        }
    }

    /// Create the service (auto-start), configure auto-restart and start it.
    pub fn install(cfg: &config::Config) -> R {
        // Datenordner (config.json/state.json/agent.log) gegen Manipulation durch
        // against normal users - done here because install has admin rights.
        harden_data_dir();
        // A dedicated service account needs write access to the data folder
        // (state.json, agent.log) - SYSTEM+Administrators is not enough then.
        if let Some(acct) = &cfg.service_account {
            let dir = config::data_dir();
            let status = std::process::Command::new(config::system32("icacls.exe"))
                .arg(&dir)
                .args(["/grant", &format!("{acct}:(OI)(CI)M")])
                .status();
            match status {
                Ok(st) if st.success() => config::log(&format!(
                    "Data folder ACL: granted Modify to service account '{acct}'."
                )),
                _ => config::log(&format!(
                    "WARNING: could not grant '{acct}' rights on {} - \
                     please grant Modify manually, otherwise the service can \
                     write neither watermarks nor its log.",
                    dir.display()
                )),
            }
        }
        // Copy the EXE to the protected location and register the service there.
        let target_exe = install_dir().join("ntlm-agent.exe");
        let current = std::env::current_exe()?;
        if !same_file(&current, &target_exe) {
            std::fs::create_dir_all(install_dir())
                .map_err(|e| format!("creating target dir {}: {e}", install_dir().display()))?;
            std::fs::copy(&current, &target_exe).map_err(|e| {
                format!(
                    "copying the EXE to {} failed: {e} \
                     (is an old service still running? then run 'uninstall' first)",
                    target_exe.display()
                )
            })?;
            config::log(&format!("EXE installed to {}", target_exe.display()));
        }

        let manager = ServiceManager::local_computer(
            None::<&str>,
            ServiceManagerAccess::CONNECT | ServiceManagerAccess::CREATE_SERVICE,
        )
        .map_err(|e| format!("connecting to the service manager failed: {e:?}"))?;

        // Does the service already exist? Say so clearly instead of failing in
        // create_service with a generic winapi error.
        if let Ok(existing) = manager.open_service(SERVICE_NAME, ServiceAccess::QUERY_STATUS) {
            let state = existing
                .query_status()
                .map(|s| format!("{:?}", s.current_state))
                .unwrap_or_else(|_| String::from("unknown"));
            return Err(format!(
                "The service '{SERVICE_NAME}' already exists (state: {state}). \
                 Please run 'ntlm-agent.exe uninstall' first, then install again. \
                 Note: if it was just uninstalled and is stuck in 'marked for \
                 deletion', close any open services.msc window and wait a moment."
            )
            .into());
        }

        // Service account: the default stays LocalSystem. With --service-account
        // the service runs under a normal account or a gMSA (trailing '$', no
        // password - Windows retrieves it from AD itself). Local names without a
        // domain part get ".\\" prefixed, otherwise the SCM does not accept them.
        let account_name: Option<OsString> = cfg.service_account.as_ref().map(|a| {
            let a = a.trim();
            if a.contains('\\') || a.contains('@') {
                OsString::from(a)
            } else {
                OsString::from(format!(".\\{a}"))
            }
        });
        let account_password: Option<OsString> = cfg.service_password.as_ref().map(OsString::from);

        let info = ServiceInfo {
            name: OsString::from(SERVICE_NAME),
            display_name: OsString::from(DISPLAY_NAME),
            service_type: SERVICE_TYPE,
            start_type: ServiceStartType::AutoStart,
            error_control: ServiceErrorControl::Normal,
            executable_path: target_exe,
            launch_arguments: vec![OsString::from("service")],
            dependencies: vec![],
            account_name, // None = LocalSystem
            account_password,
        };

        let service = manager
            .create_service(
                &info,
                ServiceAccess::CHANGE_CONFIG | ServiceAccess::START | ServiceAccess::QUERY_STATUS,
            )
            .map_err(|e| format!("creating the service failed: {e:?}"))?;
        let _ = service.set_description(
            "Collects NTLM usage data of this machine and reports it to the NTLM-Analyzer collector.",
        );

        // Automatic restart after a crash. Set via sc.exe - more robust and less
        // version-dependent than the crate's failure-actions API.
        //   reset=   reset the counter after 86400 s (1 day)
        //   actions= restart 60 s after each of the first crashes
        let _ = std::process::Command::new(config::system32("sc.exe"))
            .args([
                "failure",
                SERVICE_NAME,
                "reset=",
                "86400",
                "actions=",
                "restart/60000/restart/60000/restart/60000",
            ])
            .status();

        let no_args: Vec<OsString> = Vec::new();
        let acct_hint = if cfg.service_account.is_some() {
            " With a service account the usual causes are: (1) the account lacks \
             the 'Log on as a service' right (error 1069; grant it via GPO under \
             Computer Configuration > Windows Settings > Security Settings > \
             Local Policies > User Rights Assignment). \
             (2) gMSA: the machine may not retrieve the password - its computer \
             account is missing from PrincipalsAllowedToRetrieveManagedPassword \
             (diagnose with Test-ADServiceAccount; reboot after group changes)."
        } else {
            ""
        };
        service.start(&no_args).map_err(|e| {
            format!(
                "The service was created but starting it failed: {e:?} - \
                 details in C:\\ProgramData\\NtlmAgent\\agent.log or in Event \
                 Viewer (System). Start manually: 'sc start {SERVICE_NAME}'.{acct_hint}"
            )
        })?;

        let acct_txt = cfg
            .service_account
            .clone()
            .unwrap_or_else(|| String::from("LocalSystem"));
        config::log(&format!(
            "Service '{SERVICE_NAME}' installed and started \
             (account: {acct_txt}, interval {} min).",
            cfg.interval_minutes
        ));
        Ok(())
    }

    /// Stop the service (if still running) and remove it.
    pub fn uninstall() -> R {
        let manager = ServiceManager::local_computer(None::<&str>, ServiceManagerAccess::CONNECT)
            .map_err(|e| format!("connecting to the service manager failed: {e:?}"))?;
        let service = manager
            .open_service(
                SERVICE_NAME,
                ServiceAccess::STOP | ServiceAccess::DELETE | ServiceAccess::QUERY_STATUS,
            )
            .map_err(|e| {
                format!(
                    "Service '{SERVICE_NAME}' not found or not accessible: {e:?} \
                     (is it installed at all? check 'sc query {SERVICE_NAME}'; \
                     admin rights required)"
                )
            })?;

        if service.query_status()?.current_state != ServiceState::Stopped {
            let _ = service.stop();
            std::thread::sleep(Duration::from_secs(2));
        }
        service
            .delete()
            .map_err(|e| format!("deleting the service failed: {e:?}"))?;
        Ok(())
    }
}

#[cfg(not(windows))]
mod stub_impl {
    use crate::config;

    type R = Result<(), Box<dyn std::error::Error>>;

    fn not_supported() -> R {
        Err("The Windows service is only available on Windows.".into())
    }

    pub fn run() -> R {
        not_supported()
    }
    pub fn harden_data_dir() {}
    pub fn install(_cfg: &config::Config) -> R {
        not_supported()
    }
    pub fn uninstall() -> R {
        not_supported()
    }
}
